language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository
script:
  ./gradlew build